-- Ручной сид организации и membership (если не применяли миграцию 20250411140000).
-- Для демо-пользователя demo@revenygo.local проще выполнить миграции из supabase/migrations/
-- (там уже создаются org slug `demo` и organization_members).
--
-- Пример: своя организация и привязка пользователя по UUID из Dashboard → Authentication → Users
--
-- INSERT INTO public.organizations (id, name, slug)
-- VALUES ('aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa', 'My Org', 'my-org');
--
-- INSERT INTO public.organization_members (organization_id, user_id, role)
-- VALUES (
--   'aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa',
--   'YOUR_AUTH_USER_UUID',
--   'owner'
-- );
